language: java
jdk: openjdk8
sudo: false
deploy:
  provider: releases
  api_key:
    secure: niMRcHio8UrfXDvvZdxqMAuJUUdqtwJ9XB0UMV4aJh/8lsQ+XY+c8P/KEU0FUF/ZDtLSgV4I7WmXtqTm/G8mBSFD7aJ0oft5Uke7fT6ibP3Q2ar5L8frvEjkgr8tk9lMxKuaRmb5Upz1/76wEUH0+nZk1WTWzlPYpkAKyHchkVg6xmNkQ6d0N71e9ip7NqfS9VyKeSIDFMVWP7GaCtNeRy0S1SGZRWIamIxEFKwaBUMyQ4+bv4EHng95yHkEr8stzZIBNn5ZFNY4o+cTEPxkmLcAlHqYPCPfV2UisOnnqGXzz3URKqXposj3FDj+iTj04kWNjLyaWdz3ZVj0GKdwQEBZcCFIKnu6t3BrhvN42PUL8JNRSsZaJVYbsyOK54r6XeU+Fj6uRGikyR1MTq2uML1PnUqA19RpCnzFyCBKfzhcOyUkPNyNmeIvVhdWqv3t9DNJ0gO7X8KkQwvnHotjRkkmzRFWGyQWnIXIB7Gk4nIu1Qad/avjxG7mAphhRQ4g6Nmss6qL8gRrwwdMlioZqNQV1n4bBJzGW3bos6bUq3a33rK5/50Teg3hsl0FlDp4Gv6xG6JeIGOSvqLnlvNAqdoiLkZhVyTPTBFCOcFuClmXZACvuSxuI8IaK6R18kCQ82OHFTx4NzG3t2tOQiTFwb9WFd3dRZvIiM9/7/zlwlQ=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-redmine-plugin

